import 'antd/dist/reset.css'; // Import Ant Design base styles
import './globals.css';
import { ConfigProvider } from 'antd';
import customTheme from '../theme';




export const metadata = {
  title: 'My App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ConfigProvider theme={customTheme}>{children}</ConfigProvider>
      </body>
    </html>
  );
}